service: mono-pipe-core-orders

plugins:
  - serverless-offline

custom:
    serverless-offline:
        httpPort: 3006
        lambdaPort: 3008

provider:
  name: aws
  runtime: nodejs18.x

functions:
  main:
    handler: ../../dist/apps/pipe-core-orders/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'