service: mono-pipe-core-my-app

plugins:
  - serverless-offline

custom:
    serverless-offline:
        httpPort: 3003
        lambdaPort: 3005

provider:
  name: aws
  runtime: nodejs18.x
  profile: allied-homologa 

functions:
  my-app:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
